/**
 * Style reminder — Palm Archive: tropical-modern editorial, warm paper, teak typography,
 * asymmetric field-note flow, numbered navigation, and factual confidence without hype.
 */
import { useEffect, useMemo, useState } from "react";
import { Link } from "wouter";
import { ArrowDownRight, ArrowUpRight, Car, Check, ChevronDown, CircleAlert, Coffee, ExternalLink, Globe2, Mail, MapPinned, Menu, Navigation, Plane, ShieldCheck, Sparkles, TrainFront, TreePalm, X } from "lucide-react";
import { SITE_NAME, SITE_URL } from "@/const";

type Language = "id" | "en";

const assets = {
  logo: "/villa-tomang-logo.png",
  pattern: "/villa-tomang-pattern.png",
  walkway: "/villa-tomang-walkway.png",
  amenities: "/villa-tomang-amenities.png",
  wayfinding: "/villa-tomang-wayfinding.png",
};

const mapUrl = "https://www.google.com/maps/search/?api=1&query=Villa%20Tomang%20Baru%2C%20Jl.%20Villa%20Tomang%20Baru%2C%20Kuta%20Jaya%2C%20Pasar%20Kemis%2C%20Tangerang%2C%20Banten%2015560%2C%20Indonesia";
const embedUrl = "https://www.google.com/maps?q=Villa+Tomang+Baru,+Jl.+Villa+Tomang+Baru,+Kuta+Jaya,+Pasar+Kemis,+Tangerang,+Banten+15560,+Indonesia&z=15&output=embed&hl=id";

const text = {
  id: {
    tag: "PANDUAN LAPANGAN INDEPENDEN · PASAR KEMIS",
    titleA: "Baca kawasan ini",
    titleB: "dengan pelan.",
    lead: "Catatan kunjungan yang lugas untuk Villa Tomang Baru—sebuah kawasan hunian berpagar di Kuta Jaya, Kabupaten Tangerang.",
    start: "Mulai membaca", map: "Buka di Google Maps", language: "English", menu: "Menu", close: "Tutup",
    nav: ["Tentang", "Rencana kunjungan", "Rute", "Kebutuhan", "Tanya jawab", "Umpan balik"],
    verified: "TERCATAT DI PETA", guarded: "KAWASAN HUNIAN BERPAGAR", notice: "Rincian akses dan fasilitas dapat berubah. Konfirmasikan kebutuhan penting sebelum berangkat.",
    recordTitle: "Rekaman tempat dan konteks kawasan.",
    recordLead: "Villa Tomang Baru muncul pada Google Maps sebagai kawasan hunian berpagar. Dalam konteks yang lebih luas, profil resmi Kecamatan Pasar Kemis mencatat pemisahan wilayah dari Rajeg pada 1948, pembentukan kecamatan pada 1950, dan perkembangan Kuta Jaya dari Kutabumi pada 1982. Panduan ini memakai sejarah administratif yang dapat ditelusuri, bukan menciptakan legenda khusus tempat ini.",
    facts: [["Alamat", "Jl. Villa Tomang Baru, Kuta Jaya, Kec. Ps. Kemis, Kabupaten Tangerang, Banten 15560"], ["Koordinat", "-6.1545721, 106.5812535"], ["Kategori peta", "Gated community / kawasan hunian berpagar"], ["Rating peta", "4,4 / 5 dari 257 ulasan publik*"], ["Jam operasional", "Tidak tercantum pada profil peta publik"], ["Biaya masuk", "Tidak tercantum; ini bukan objek wisata berkarcis"]],
    contextEyebrow: "KONTEKS WILAYAH · BUKAN LEGENDA YANG DIBUAT-BUAT", contextTitle: "Sebuah catatan kecil dalam riwayat Pasar Kemis.", contextLead: "Villa Tomang Baru berada di Kelurahan Kuta Jaya, dalam Kecamatan Pasar Kemis. Profil resmi kecamatan mencatat Pasar Kemis terpisah dari Rajeg pada 1948 dan menjadi kecamatan pada 1950; Kutabumi kemudian dimekarkan dengan Kuta Jaya pada 1982. Rangkaian administratif ini memberi konteks mengapa kawasan hunian, koridor layanan sehari-hari, dan rute lokal saling berdekatan.", contextCards: [["Yang dapat dikonfirmasi", "Riwayat administratif Pasar Kemis dan perkembangan Kuta Jaya dapat ditelusuri pada profil pemerintah kecamatan."], ["Yang tidak kami tuliskan", "Kami tidak menemukan cerita sejarah, legenda, atau asal-usul yang dapat diverifikasi khusus untuk Villa Tomang Baru. Karena itu, panduan tidak akan menciptakan narasi yang seolah-olah faktual."], ["Mengapa konteks penting", "Memahami bahwa ini adalah lingkungan hidup membantu pengunjung memilih tujuan yang jelas, menggunakan akses secara wajar, dan menghormati ketenangan warga."]], contextSource: "Baca riwayat resmi Kecamatan Pasar Kemis",
    foot: "*Data rating bersifat dinamis dan ditampilkan sebagai konteks, bukan rekomendasi. Riwayat wilayah dirujuk dari profil resmi Kecamatan Pasar Kemis.",
    planEyebrow: "01 · SEBELUM BERANGKAT", planTitle: "Rencanakan dengan hormat terhadap lingkungan hunian.",
    planIntro: "Karena ini adalah kawasan tempat tinggal, kualitas kunjungan ditentukan oleh persiapan kecil: gunakan navigasi, pilih waktu yang tidak mengganggu, dan patuhi arahan keamanan di lokasi.",
    planCards: [["Waktu terbaik", "Pagi atau sore hari biasanya lebih nyaman untuk cuaca tropis. Tidak ada jam kunjungan resmi yang dipublikasikan—hindari mengasumsikan akses bebas."], ["Durasi yang disarankan", "Rencanakan sekitar 20–40 menit untuk orientasi rute dan kebutuhan praktis di sekitar kawasan. Tambahkan waktu hanya jika Anda memiliki tujuan yang jelas."], ["Etika & akses", "Jaga kebisingan, jangan menghalangi gerbang atau jalan lingkungan, dan jangan memotret rumah maupun penghuni tanpa izin."], ["Toilet & kebutuhan dasar", "Ketersediaan toilet umum, ruang ibadah, dan fasilitas tamu tidak terkonfirmasi pada profil publik. Siapkan kebutuhan sebelum tiba."], ["Air minum & cuaca", "Bawa air minum, pelindung hujan, dan alas kaki yang sesuai. Kunjungan singkat tetap membutuhkan persiapan untuk cuaca panas atau hujan setempat."], ["Kontak & tujuan", "Simpan alamat lengkap, koordinat, serta tujuan kunjungan sebelum berangkat. Petugas keamanan atau warga tidak berkewajiban mengarahkan kunjungan yang tidak jelas."]],
    travelEyebrow: "02 · MENUJU LOKASI", travelTitle: "Datang secara bertahap, lalu cek langkah terakhir.", travelIntro: "Villa Tomang Baru tidak berada di terminal bandara atau simpul rel. Rencanakan perjalanan sebagai beberapa tahap: masuk ke wilayah Tangerang, berpindah ke transportasi lokal, lalu periksa titik tujuan serta izin akses. Waktu tempuh dan tarif bersifat dinamis.",
    routes: [["Dari bandara", "Dari Bandara Internasional Soekarno–Hatta, opsi paling langsung umumnya adalah taksi resmi, kendaraan sewaan, atau layanan transportasi daring menuju alamat lengkap. Bus bandara dapat membantu masuk ke jaringan transportasi Jakarta, tetapi bukan layanan langsung ke Villa Tomang Baru."], ["Kereta & angkutan lanjutan", "Gunakan layanan Commuter Line untuk mendekati wilayah Tangerang sesuai titik asal Anda. Sesudah turun, periksa peta untuk angkutan lanjutan yang sesuai; tidak ada stasiun kereta di dalam kawasan tujuan."], ["Bus & transportasi lokal", "Bus kota/antarwilayah dapat berguna pada bagian awal perjalanan, tetapi rute dan titik turun perlu diperiksa pada hari berangkat. Lanjutkan dengan angkutan lokal, ojek, atau taksi hanya setelah tujuan terakhir sudah jelas."], ["Taksi, ojek & kendaraan pribadi", "Masukkan alamat dan koordinat yang sama ke aplikasi navigasi. Jika memasuki kawasan hunian, jangan memaksa akses, memblokir pintu masuk, atau menganggap pengemudi dapat berhenti di lokasi mana pun."]],
    parkingTitle: "Catatan parkir", parkingBody: "Ketersediaan, aturan, dan kapasitas parkir khusus pengunjung tidak tercantum pada sumber publik yang kami periksa. Jangan menganggap parkir di dalam kawasan tersedia; ikuti marka dan arahan setempat.",
    aroundEyebrow: "03 · KEBUTUHAN PRAKTIS", aroundTitle: "Cari layanan berdasarkan jenis, bukan nama dagang.", aroundIntro: "Sebagai panduan non-profit yang netral, kami tidak mempromosikan usaha tertentu. Gunakan peta publik untuk menyaring berdasarkan jenis layanan, jam buka, aksesibilitas, dan jarak aktual dari titik Anda pada hari perjalanan.",
    aroundCards: [["WC & kebersihan diri", "WC umum atau fasilitas tamu di dalam kawasan tidak terkonfirmasi. Gunakan toilet di titik transit atau layanan umum sebelum tiba; jangan menganggap fasilitas penghuni dapat dipakai pengunjung."], ["Parkir & titik turun", "Aturan parkir pengunjung tidak dipublikasikan. Tentukan titik turun yang tidak mengganggu gerbang atau jalan lingkungan, lalu ikuti marka dan arahan di tempat."], ["Makan & air minum", "Cari warung, kedai, restoran keluarga, atau toko minuman di koridor jalan yang lebih ramai. Bawa air minum untuk kunjungan singkat, terutama saat cuaca panas."], ["Belanja sehari-hari", "Untuk kebutuhan ringan, cari minimarket, toko kebutuhan harian, atau pasar lingkungan. Periksa jam buka dan metode pembayaran sebelum bergantung pada satu titik."], ["Menginap", "Jika perlu bermalam, cari akomodasi di wilayah Tangerang berdasarkan rute perjalanan, kebutuhan akses, dan waktu keberangkatan berikutnya—bukan berdasarkan nama yang direkomendasikan situs ini."], ["Bahan bakar & pengisian", "Pengemudi kendaraan pribadi sebaiknya memeriksa stasiun pengisian bahan bakar atau titik pengisian daya pada aplikasi peta sebelum memasuki rute lokal."], ["Kesehatan, obat & uang tunai", "Cari fasilitas kesehatan, apotek, ATM, atau layanan pembayaran yang sesuai kebutuhan aktual melalui peta. Bawa kebutuhan pribadi yang penting karena fasilitas di dalam kawasan tidak dikonfirmasi."], ["Ruang istirahat & ibadah", "Ketersediaan ruang istirahat, musala, atau area teduh bagi pengunjung tidak tercantum pada profil publik. Persiapkan jeda perjalanan di luar kawasan bila diperlukan."]],
    mapEyebrow: "04 · ORIENTASI", mapTitle: "Gunakan peta untuk langkah terakhir.", mapLead: "Lokasi dapat berubah secara kontekstual dari satu gerbang ke gerbang lain. Buka peta langsung untuk rute, kondisi lalu lintas, dan detail navigasi terbaru.",
    faqEyebrow: "05 · PERTANYAAN YANG SERING DITANYAKAN", faqTitle: "Yang diketahui, dan yang belum dapat dipastikan.",
    faqs: [["Apakah Villa Tomang Baru adalah objek wisata?", "Tidak. Profil peta publik mengklasifikasikannya sebagai kawasan hunian berpagar. Panduan ini tidak menyajikannya sebagai taman hiburan atau tempat wisata berkarcis."], ["Apakah ada tiket atau biaya masuk?", "Tidak ada informasi biaya masuk yang tercantum pada profil publik yang kami periksa. Jangan menganggap akses atau fasilitas tertentu tersedia tanpa konfirmasi."], ["Bagaimana dari bandara atau dengan bus?", "Perjalanan perlu direncanakan dalam beberapa tahap. Bandara dan jaringan bus/kereta memberi akses menuju wilayah Tangerang atau Jakarta, tetapi bukan rute langsung ke Villa Tomang Baru. Periksa rute, jadwal, dan sambungan lokal pada hari perjalanan."], ["Apakah tersedia WC atau parkir umum?", "Kami tidak menemukan ketentuan pengunjung yang dipublikasikan untuk WC maupun parkir di dalam kawasan. Gunakan fasilitas sebelum tiba dan ikuti tanda serta arahan di lokasi."], ["Kapan waktu terbaik untuk berkunjung?", "Pagi atau sore dapat terasa lebih nyaman secara iklim. Namun tidak ada jadwal kunjungan resmi yang dipublikasikan, sehingga akses tetap perlu dipastikan."], ["Apakah ada sejarah atau legenda tempat ini?", "Ada sejarah administratif Pasar Kemis dan Kuta Jaya yang terdokumentasi pada sumber pemerintah. Kami tidak menemukan legenda khusus Villa Tomang Baru yang dapat diverifikasi, sehingga tidak menuliskannya sebagai fakta."], ["Bolehkah memotret?", "Hormati privasi penghuni. Hindari mengambil foto rumah, orang, atau pos keamanan tanpa persetujuan yang sesuai."], ["Bagaimana mengirim koreksi?", "Gunakan tautan umpan balik di bawah atau kirim email. Sertakan sumber publik atau konteks yang cukup agar kami dapat meninjau catatan dengan hati-hati."]],
    feedbackEyebrow: "06 · BANTU MEMPERBAIKI CATATAN", feedbackTitle: "Melihat informasi yang perlu diperbaiki?", feedbackLead: "Kirim koreksi, sumber publik, atau catatan akses yang bermanfaat. Pesan Anda membantu panduan ini tetap jelas tanpa berubah menjadi daftar rekomendasi komersial.", feedback: "Kirim umpan balik", legal: ["Privasi", "Ketentuan", "Cookie"],
    footer: "Panduan informasi pengunjung independen dan tidak berafiliasi dengan pemerintah, pengelola kawasan, maupun organisasi resmi mana pun.", footer2: "Informasi lokasi diringkas dari profil peta publik dan dilabeli sesuai tingkat verifikasinya. Tidak ada rekomendasi komersial dalam panduan ini.", copyright: "© 2026 Villa Tomang Baru Field Guide. Hak cipta teks dan rancangan dilindungi.", imageCredit: "Ilustrasi visual dibuat untuk panduan ini; peta disematkan dari Google Maps.",
  },
  en: {
    tag: "INDEPENDENT FIELD GUIDE · PASAR KEMIS",
    titleA: "Read this place", titleB: "at an unhurried pace.",
    lead: "A straightforward visit note for Villa Tomang Baru—a gated residential community in Kuta Jaya, Tangerang Regency.",
    start: "Start reading", map: "Open in Google Maps", language: "Bahasa Indonesia", menu: "Menu", close: "Close",
    nav: ["About", "Plan a visit", "Getting there", "Practical needs", "FAQ", "Feedback"],
    verified: "MAPPED RECORD", guarded: "GATED RESIDENTIAL COMMUNITY", notice: "Access details and facilities may change. Confirm anything important before you leave.",
    recordTitle: "A place record and its local context.",
    recordLead: "Google Maps identifies Villa Tomang Baru as a gated residential community. In the wider context, Pasar Kemis District’s official profile records separation from Rajeg in 1948, its formation as a district in 1950, and the development of Kuta Jaya from Kutabumi in 1982. This guide uses traceable administrative history rather than inventing a place-specific legend.",
    facts: [["Address", "Jl. Villa Tomang Baru, Kuta Jaya, Kec. Ps. Kemis, Kabupaten Tangerang, Banten 15560"], ["Coordinates", "-6.1545721, 106.5812535"], ["Map category", "Gated community"], ["Map rating", "4.4 / 5 from 257 public reviews*"], ["Opening hours", "Not listed on the public map profile"], ["Entry fees", "Not listed; this is not a ticketed attraction"]],
    contextEyebrow: "LOCAL CONTEXT · NOT INVENTED LEGEND", contextTitle: "A small record within the history of Pasar Kemis.", contextLead: "Villa Tomang Baru sits in Kuta Jaya, within Pasar Kemis District. The district’s official profile records that Pasar Kemis separated from Rajeg in 1948 and became a district in 1950; Kutabumi was later expanded with Kuta Jaya in 1982. This administrative sequence gives useful context for the close relationship between housing, everyday-service corridors, and local routes.", contextCards: [["What can be checked", "The administrative history of Pasar Kemis and the development of Kuta Jaya can be traced in the district government’s profile."], ["What we do not write", "We found no verified story, legend, or origin narrative specific to Villa Tomang Baru. This guide will not create one and present it as fact."], ["Why the context matters", "Knowing that this is a lived-in community helps visitors choose a clear purpose, use access reasonably, and respect residents’ quiet."]], contextSource: "Read the Pasar Kemis District’s official history",
    foot: "*Rating data is dynamic and shown for context, not as an endorsement. Local history is referenced from the Pasar Kemis District’s official profile.",
    planEyebrow: "01 · BEFORE YOU GO", planTitle: "Plan with respect for a residential setting.",
    planIntro: "Because this is a place where people live, a good visit starts with small preparations: use navigation, choose a considerate time, and follow local security directions.",
    planCards: [["Best time", "Morning or late afternoon may be more comfortable in the tropical climate. No official visitor hours are published—do not assume unrestricted access."], ["Suggested duration", "Allow roughly 20–40 minutes for route orientation and nearby practical needs. Add time only when you have a clear purpose."], ["Etiquette & access", "Keep noise down, do not block gates or neighbourhood roads, and do not photograph homes or residents without permission."], ["Toilets & basics", "Public toilets, prayer spaces, and visitor facilities are not confirmed on the public profile. Prepare your essentials before arriving."], ["Water & weather", "Carry drinking water, rain protection, and suitable footwear. Even a short visit benefits from preparation for local heat or rain."], ["Contact & destination", "Save the full address, coordinates, and a clear purpose before leaving. Security staff and residents are not obliged to direct an undefined visit."]],
    travelEyebrow: "02 · GETTING THERE", travelTitle: "Arrive in stages, then check the final approach.", travelIntro: "Villa Tomang Baru is not at an airport terminal or a rail hub. Plan the journey in stages: reach the Tangerang area, transfer to local transport, then check the destination point and access terms. Times and fares are dynamic.",
    routes: [["From the airport", "From Soekarno–Hatta International Airport, the most direct options are usually an official taxi, a hired car, or a ride-hailing service to the full address. Airport buses can help reach the wider Jakarta transport network, but do not run directly to Villa Tomang Baru."], ["Rail & onward connection", "Use Commuter Line services to approach the Tangerang area from your starting point. After alighting, check a map for the appropriate local connection; there is no rail station inside the destination community."], ["Bus & local transport", "City or intercity buses can be useful in the early stages, but routes and drop-off points need checking on the travel day. Continue by local transport, motorcycle taxi, or taxi only after the final destination is clear."], ["Taxi, motorcycle taxi & private vehicle", "Enter the same address and coordinates into a navigation app. When entering a residential community, do not force access, obstruct gates, or assume a driver may stop anywhere."]],
    parkingTitle: "Parking note", parkingBody: "Availability, rules, and capacity for visitor parking are not listed in the public sources we checked. Do not assume parking is available inside the estate; follow markings and local directions.",
    aroundEyebrow: "03 · PRACTICAL NEEDS", aroundTitle: "Find services by type, not by brand.", aroundIntro: "As a neutral, non-profit guide, we do not promote individual businesses. Use public maps to filter by service type, opening hours, accessibility, and the real distance from your location on the day you travel.",
    aroundCards: [["Toilets & hygiene", "Public toilets or guest facilities inside the community are not confirmed. Use facilities at a transport interchange or public service point before arrival; do not assume residents’ facilities are for visitors."], ["Parking & drop-off", "Visitor-parking terms are not published. Choose a drop-off point that does not disrupt gates or neighbourhood roads, then follow markings and local directions."], ["Food & drinking water", "Look for food stalls, cafés, family restaurants, or drink shops along busier road corridors. Carry water for a short visit, particularly in warm weather."], ["Daily supplies", "For small needs, look for convenience stores, daily-needs shops, or neighbourhood markets. Check hours and payment methods before relying on one location."], ["Stays", "If you need an overnight stop, search the Tangerang area by travel route, access needs, and your next departure time—not by a name endorsed by this site."], ["Fuel & charging", "Private-vehicle drivers should check fuel stations or charging points in a map app before entering local roads."], ["Health, pharmacy & cash", "Find health facilities, pharmacies, cash points, or payment services for your actual needs in a map app. Carry essential personal supplies because on-site amenities are not confirmed."], ["Rest & prayer", "Visitor rest areas, prayer rooms, or shaded space are not listed on the public profile. Plan travel breaks outside the community if required."]],
    mapEyebrow: "04 · ORIENT YOURSELF", mapTitle: "Use the map for the final approach.", mapLead: "The practical route can vary from one entrance to another. Open the live map for routing, traffic, and the latest navigation detail.",
    faqEyebrow: "05 · FREQUENTLY ASKED QUESTIONS", faqTitle: "What is known, and what cannot yet be confirmed.",
    faqs: [["Is Villa Tomang Baru a tourist attraction?", "No. Its public map profile classifies it as a gated residential community. This guide does not present it as a theme park or ticketed attraction."], ["Is there an entry ticket or fee?", "No fee information appears in the public profile we checked. Do not assume access to an area or facility without confirmation."], ["How do I arrive from the airport or by bus?", "Plan the trip in stages. The airport and bus/rail networks provide access towards Tangerang or Jakarta, but not a direct route to Villa Tomang Baru. Check routes, timetables, and local connections on your travel day."], ["Are toilets or public parking available?", "We found no published visitor terms for toilets or parking inside the community. Use facilities before arriving and follow all on-site signs and directions."], ["When is the best time to visit?", "Morning or late afternoon may feel more comfortable climatically. There are no published official visitor hours, so access still needs checking."], ["Is there a history or legend for this place?", "There is documented administrative history for Pasar Kemis and Kuta Jaya in government sources. We found no verified legend specific to Villa Tomang Baru, so we do not publish one as fact."], ["May I take photographs?", "Respect residents’ privacy. Avoid photographing homes, people, or security posts without suitable permission."], ["How can I submit a correction?", "Use the feedback link below or send an email. Include a public source or enough context for a careful review."]],
    feedbackEyebrow: "06 · HELP IMPROVE THE RECORD", feedbackTitle: "Spotted information that needs correcting?", feedbackLead: "Send a correction, a public source, or a useful access note. Your message helps keep this guide clear without turning it into a commercial recommendation list.", feedback: "Send feedback", legal: ["Privacy", "Terms", "Cookies"],
    footer: "An independent visitor-information guide with no affiliation to government, estate management, or any official organisation.", footer2: "Location information is summarised from public map records and labelled by its level of verification. This guide contains no commercial recommendations.", copyright: "© 2026 Villa Tomang Baru Field Guide. Original writing and design are protected.", imageCredit: "Visual illustrations were created for this guide; the map is embedded from Google Maps.",
  },
} as const;

const sections = ["about", "plan", "travel", "nearby", "faq", "feedback"];

function loadGoogleAnalytics() {
  if (document.querySelector('script[data-vtb-ga="true"]')) return;
  const script = document.createElement("script");
  script.async = true;
  script.src = "https://www.googletagmanager.com/gtag/js?id=G-HXM22WWPKP";
  script.dataset.vtbGa = "true";
  document.head.appendChild(script);
  window.dataLayer = window.dataLayer || [];
  window.gtag = (...args: unknown[]) => window.dataLayer!.push(args);
  window.gtag("js", new Date());
  window.gtag("config", "G-HXM22WWPKP", { anonymize_ip: true });
}

declare global { interface Window { dataLayer?: unknown[]; gtag?: (...args: unknown[]) => void; } }

export default function Home() {
  const [lang, setLang] = useState<Language>(() => (typeof window !== "undefined" && localStorage.getItem("vtb-lang") === "en" ? "en" : "id"));
  const [menuOpen, setMenuOpen] = useState(false);
  const [openFaq, setOpenFaq] = useState<number | null>(0);
  const c = text[lang];
  const jsonLd = useMemo(() => ({
    "@context": "https://schema.org", "@type": "Place", name: "Villa Tomang Baru", description: lang === "id" ? "Panduan independen untuk konteks lokasi Villa Tomang Baru di Kuta Jaya." : "An independent guide to the location context of Villa Tomang Baru in Kuta Jaya.",
    address: { "@type": "PostalAddress", streetAddress: "Jl. Villa Tomang Baru", addressLocality: "Kuta Jaya, Pasar Kemis", addressRegion: "Banten", postalCode: "15560", addressCountry: "ID" },
    geo: { "@type": "GeoCoordinates", latitude: -6.1545721, longitude: 106.5812535 },
    aggregateRating: { "@type": "AggregateRating", ratingValue: 4.4, reviewCount: 257, bestRating: 5, worstRating: 1 },
    ...(SITE_URL ? { url: SITE_URL } : {}),
  }), [lang]);
  const faqLd = useMemo(() => ({ "@context": "https://schema.org", "@type": "FAQPage", mainEntity: c.faqs.map(([q, a]) => ({ "@type": "Question", name: q, acceptedAnswer: { "@type": "Answer", text: a } })) }), [c.faqs]);

  useEffect(() => {
    document.documentElement.lang = lang;
    document.title = lang === "id" ? "Villa Tomang Baru · Panduan Lapangan" : SITE_NAME;
    let canonical = document.querySelector('link[rel="canonical"]') as HTMLLinkElement | null;
    if (SITE_URL) { if (!canonical) { canonical = document.createElement("link"); canonical.rel = "canonical"; document.head.appendChild(canonical); } canonical.href = SITE_URL; }
    if (localStorage.getItem("vtb-analytics") === "true") loadGoogleAnalytics();
  }, [lang]);

  const changeLanguage = (next: Language) => { setLang(next); localStorage.setItem("vtb-lang", next); };
  const go = (id: string) => { document.getElementById(id)?.scrollIntoView({ behavior: "smooth", block: "start" }); setMenuOpen(false); };

  return <main className="overflow-x-hidden bg-[#F5EFE3] text-[#31251F] selection:bg-[#C86F4D]/30">
    <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }} />
    <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(faqLd) }} />
    <header className="relative z-30 border-b border-[#4A352C]/15 bg-[#F5EFE3]/92 px-5 py-4 backdrop-blur-xl md:px-10">
      <div className="mx-auto flex max-w-[1440px] items-center justify-between gap-5">
        <button aria-label="Back to top" onClick={() => go("top")} className="flex items-center gap-3 text-left"><img src={assets.logo} alt="" className="h-11 w-11 object-contain" /><span><span className="block font-display text-xl leading-none text-[#34251E]">Villa Tomang Baru</span><span className="mt-1 block font-mono text-[9px] font-bold tracking-[0.16em] text-[#5B7A5A]">FIELD GUIDE / 2026</span></span></button>
        <nav className="hidden items-center gap-5 xl:flex">{c.nav.slice(0, 5).map((item, index) => <button key={item} onClick={() => go(sections[index])} className="text-xs font-bold tracking-wide text-[#5B5146] transition hover:text-[#5B7A5A]">{item}</button>)}</nav>
        <div className="flex items-center gap-2"><button onClick={() => changeLanguage(lang === "id" ? "en" : "id")} className="inline-flex h-10 items-center gap-2 rounded-full border border-[#4A352C]/20 bg-white/50 px-3 text-xs font-bold text-[#4A352C] transition hover:border-[#5B7A5A] hover:text-[#5B7A5A]"><Globe2 size={15} /> <span className="hidden sm:inline">{c.language}</span><span className="sm:hidden">{lang === "id" ? "EN" : "ID"}</span></button><button onClick={() => setMenuOpen(!menuOpen)} className="inline-flex h-10 w-10 items-center justify-center rounded-full border border-[#4A352C]/20 bg-white/50 text-[#4A352C] xl:hidden" aria-label={menuOpen ? c.close : c.menu}>{menuOpen ? <X size={18} /> : <Menu size={18} />}</button></div>
      </div>
      {menuOpen && <div className="absolute inset-x-0 top-full border-b border-[#4A352C]/15 bg-[#F5EFE3] px-5 py-6 shadow-xl xl:hidden"><div className="mx-auto grid max-w-[1440px] gap-2">{c.nav.map((item, index) => <button key={item} onClick={() => go(sections[index])} className="flex items-center justify-between border-b border-[#4A352C]/10 py-3 text-left font-display text-2xl text-[#34251E]">{item}<ArrowDownRight size={20} className="text-[#5B7A5A]" /></button>)}</div></div>}
    </header>

    <section id="top" className="relative min-h-[720px] overflow-hidden px-5 pb-16 pt-16 md:px-10 md:pb-24 md:pt-24"><div className="absolute inset-0 bg-[radial-gradient(circle_at_85%_20%,rgba(200,111,77,0.17),transparent_25%),radial-gradient(circle_at_12%_80%,rgba(91,122,90,0.14),transparent_22%)]" /><img src={assets.pattern} alt="" className="absolute -right-24 top-0 h-full w-[78%] max-w-[960px] object-cover opacity-65 mix-blend-multiply" />
      <div className="relative mx-auto grid max-w-[1440px] items-end gap-12 lg:grid-cols-[1.25fr_.75fr] lg:gap-20"><div className="max-w-4xl"><div className="mb-8 flex flex-wrap gap-3"><span className="inline-flex items-center gap-2 border border-[#5B7A5A]/35 bg-[#F5EFE3]/80 px-3 py-2 font-mono text-[10px] font-bold tracking-[0.14em] text-[#5B7A5A]"><Check size={13} />{c.verified}</span><span className="inline-flex items-center gap-2 border border-[#C86F4D]/30 bg-[#F5EFE3]/80 px-3 py-2 font-mono text-[10px] font-bold tracking-[0.14em] text-[#A75339]"><TreePalm size={13} />{c.guarded}</span></div><p className="mb-5 font-mono text-xs font-bold tracking-[0.18em] text-[#5B7A5A]">{c.tag}</p><h1 className="max-w-3xl font-display text-[clamp(4.3rem,9vw,9.5rem)] leading-[0.82] tracking-[-0.065em] text-[#34251E]"><span className="block">{c.titleA}</span><em className="block pl-[12%] font-display font-normal text-[#C86F4D]">{c.titleB}</em></h1><p className="mt-10 max-w-xl text-lg leading-8 text-[#655348] md:text-xl">{c.lead}</p><div className="mt-10 flex flex-wrap gap-3"><button onClick={() => go("about")} className="group inline-flex items-center gap-3 bg-[#4A352C] px-5 py-4 text-sm font-bold text-white transition hover:bg-[#5B7A5A] active:scale-[0.97]">{c.start}<ArrowDownRight size={18} className="transition-transform group-hover:translate-y-1" /></button><a href={mapUrl} target="_blank" rel="noreferrer" className="inline-flex items-center gap-3 border border-[#4A352C]/25 bg-[#F5EFE3]/65 px-5 py-4 text-sm font-bold text-[#4A352C] transition hover:border-[#5B7A5A] hover:text-[#5B7A5A] active:scale-[0.97]">{c.map}<ExternalLink size={17} /></a></div></div>
        <aside className="relative max-w-md justify-self-end border-l-2 border-[#C86F4D] bg-white/55 p-6 shadow-[18px_20px_0_rgba(74,53,44,0.08)] backdrop-blur"><CircleAlert className="mb-6 text-[#C86F4D]" size={22} /><p className="font-display text-2xl leading-tight text-[#34251E]">{c.notice}</p><div className="mt-7 flex items-end justify-between border-t border-[#4A352C]/15 pt-4"><span className="font-mono text-[10px] font-bold tracking-[0.16em] text-[#5B7A5A]">-6.1545721<br />106.5812535</span><MapPinned size={26} className="text-[#4A352C]" /></div></aside>
      </div>
    </section>

    <section id="about" className="scroll-mt-24 border-y border-[#4A352C]/15 bg-[#4A352C] px-5 py-20 text-[#F8F2E9] md:px-10 md:py-28"><div className="mx-auto grid max-w-[1280px] gap-16 lg:grid-cols-[.92fr_1.08fr]"><div><p className="font-mono text-xs font-bold tracking-[0.18em] text-[#9CB99A]">00 · {c.nav[0].toUpperCase()}</p><h2 className="mt-5 font-display text-5xl leading-[.94] tracking-tight md:text-7xl">{c.recordTitle}</h2><p className="mt-8 max-w-md text-lg leading-8 text-[#E1D6C8]">{c.recordLead}</p><p className="mt-8 max-w-md border-l border-[#C86F4D] pl-4 text-sm leading-6 text-[#CFC4B2]">{c.foot}</p></div><div className="border-t border-[#F8F2E9]/20">{c.facts.map(([label, value], i) => <div key={label} className="grid gap-3 border-b border-[#F8F2E9]/20 py-5 md:grid-cols-[150px_1fr]"><span className="font-mono text-[10px] font-bold tracking-[0.13em] text-[#9CB99A]">0{i + 1} / {label.toUpperCase()}</span><span className="text-base leading-6 text-[#F8F2E9]">{value}</span></div>)}</div></div></section>

    <section id="plan" className="scroll-mt-24 px-5 py-20 md:px-10 md:py-28"><div className="mx-auto max-w-[1280px]"><div className="grid gap-8 lg:grid-cols-[1fr_.75fr]"><div><p className="font-mono text-xs font-bold tracking-[0.18em] text-[#5B7A5A]">{c.planEyebrow}</p><h2 className="mt-5 max-w-3xl font-display text-5xl leading-[.95] tracking-tight text-[#34251E] md:text-7xl">{c.planTitle}</h2></div><p className="self-end max-w-lg border-l-2 border-[#C86F4D] pl-5 text-lg leading-8 text-[#6A574A]">{c.planIntro}</p></div><div className="mt-14 grid gap-px overflow-hidden border border-[#4A352C]/15 bg-[#4A352C]/15 sm:grid-cols-2">{c.planCards.map(([title, body], i) => <article key={title} className="bg-[#F5EFE3] p-7 transition hover:bg-[#FBF8F1] md:p-9"><span className="font-mono text-xs font-bold text-[#C86F4D]">0{i + 1}</span><h3 className="mt-7 font-display text-3xl text-[#34251E]">{title}</h3><p className="mt-4 text-sm leading-7 text-[#6A574A]">{body}</p></article>)}</div></div></section>

    <section id="travel" className="scroll-mt-24 relative overflow-hidden bg-[#E9E0D2] px-5 py-20 md:px-10 md:py-28"><img src={assets.wayfinding} alt="" className="absolute -right-28 bottom-0 h-[550px] w-[55%] object-cover opacity-20 mix-blend-multiply" /><div className="relative mx-auto max-w-[1280px]"><div className="grid gap-8 lg:grid-cols-[.7fr_1.3fr]"><div><p className="font-mono text-xs font-bold tracking-[0.18em] text-[#5B7A5A]">{c.travelEyebrow}</p><h2 className="mt-5 font-display text-5xl leading-[.95] tracking-tight text-[#34251E] md:text-7xl">{c.travelTitle}</h2></div><p className="self-end max-w-xl text-lg leading-8 text-[#6A574A]">{c.travelIntro}</p></div><div className="mt-16 grid gap-0 lg:grid-cols-4">{c.routes.map(([title, body], i) => { const Icon = [Plane, TrainFront, Navigation, Car][i]; return <article key={title} className="border-t border-[#4A352C]/25 px-0 py-8 lg:border-l lg:px-8 lg:py-0 first:pl-0"><Icon size={25} className="text-[#C86F4D]" /><h3 className="mt-8 font-display text-3xl text-[#34251E]">{title}</h3><p className="mt-4 text-sm leading-7 text-[#6A574A]">{body}</p></article>})}</div><div className="mt-8 flex flex-col gap-5 border border-[#4A352C]/20 bg-[#F5EFE3]/65 p-6 md:flex-row md:items-center md:justify-between"><div className="flex gap-4"><Car className="mt-1 shrink-0 text-[#5B7A5A]" /><div><h3 className="font-display text-2xl text-[#34251E]">{c.parkingTitle}</h3><p className="mt-2 max-w-3xl text-sm leading-6 text-[#6A574A]">{c.parkingBody}</p></div></div><a href={mapUrl} target="_blank" rel="noreferrer" className="shrink-0 text-sm font-bold text-[#4A352C] underline decoration-[#C86F4D] decoration-2 underline-offset-4 hover:text-[#5B7A5A]">{c.map} <ArrowUpRight size={15} className="inline" /></a></div></div></section>

    <section id="nearby" className="scroll-mt-24 px-5 py-20 md:px-10 md:py-28"><div className="mx-auto max-w-[1280px]"><div className="grid gap-9 lg:grid-cols-[.92fr_1.08fr]"><div><p className="font-mono text-xs font-bold tracking-[0.18em] text-[#5B7A5A]">{c.aroundEyebrow}</p><h2 className="mt-5 font-display text-5xl leading-[.95] tracking-tight text-[#34251E] md:text-7xl">{c.aroundTitle}</h2></div><p className="self-end border-l-2 border-[#C86F4D] pl-5 text-lg leading-8 text-[#6A574A]">{c.aroundIntro}</p></div><div className="mt-16 grid gap-x-10 border-t border-[#4A352C]/15 md:grid-cols-2 xl:grid-cols-3">{c.aroundCards.map(([title, body], i) => <article key={title} className="group border-b border-[#4A352C]/15 py-8"><div className="flex items-start justify-between"><span className="font-mono text-xs font-bold text-[#C86F4D]">0{i + 1}</span>{i === 0 ? <Coffee size={20} className="text-[#5B7A5A]" /> : <Sparkles size={18} className="text-[#5B7A5A] opacity-0 transition group-hover:opacity-100" />}</div><h3 className="mt-7 font-display text-3xl text-[#34251E]">{title}</h3><p className="mt-3 text-sm leading-7 text-[#6A574A]">{body}</p></article>)}</div></div></section>

    <section className="px-5 md:px-10"><div className="mx-auto grid max-w-[1440px] overflow-hidden bg-[#D4C5AE] lg:grid-cols-[.85fr_1.15fr]"><div className="p-9 md:p-14"><p className="font-mono text-xs font-bold tracking-[0.18em] text-[#5B7A5A]">{c.mapEyebrow}</p><h2 className="mt-5 font-display text-5xl leading-[.95] tracking-tight text-[#34251E] md:text-6xl">{c.mapTitle}</h2><p className="mt-7 max-w-md text-base leading-7 text-[#6A574A]">{c.mapLead}</p><a href={mapUrl} target="_blank" rel="noreferrer" className="mt-9 inline-flex items-center gap-3 bg-[#4A352C] px-5 py-4 text-sm font-bold text-white transition hover:bg-[#5B7A5A]">{c.map}<ExternalLink size={16} /></a></div><div className="min-h-[400px] border-l border-[#4A352C]/15"><iframe title="Villa Tomang Baru map" src={embedUrl} className="h-full min-h-[400px] w-full border-0 grayscale-[.15]" loading="lazy" referrerPolicy="strict-origin-when-cross-origin" allowFullScreen /></div></div></section>

    <section id="faq" className="scroll-mt-24 px-5 py-20 md:px-10 md:py-28"><div className="mx-auto grid max-w-[1280px] gap-12 lg:grid-cols-[.7fr_1.3fr]"><div><p className="font-mono text-xs font-bold tracking-[0.18em] text-[#5B7A5A]">{c.faqEyebrow}</p><h2 className="mt-5 font-display text-5xl leading-[.95] tracking-tight text-[#34251E] md:text-6xl">{c.faqTitle}</h2><img src={assets.amenities} alt="" className="mt-10 aspect-[4/3] w-full object-cover mix-blend-multiply" /></div><div className="border-t border-[#4A352C]/20">{c.faqs.map(([q, a], i) => <article key={q} className="border-b border-[#4A352C]/20"><button onClick={() => setOpenFaq(openFaq === i ? null : i)} aria-expanded={openFaq === i} className="flex w-full items-center gap-5 py-6 text-left"><span className="font-mono text-xs font-bold text-[#C86F4D]">0{i + 1}</span><span className="flex-1 font-display text-2xl leading-tight text-[#34251E] md:text-3xl">{q}</span><ChevronDown size={20} className={"shrink-0 text-[#5B7A5A] transition-transform " + (openFaq === i ? "rotate-180" : "")} /></button>{openFaq === i && <p className="max-w-2xl pb-7 pl-9 text-sm leading-7 text-[#6A574A]">{a}</p>}</article>)}</div></div></section>

    <section id="feedback" className="scroll-mt-24 bg-[#5B7A5A] px-5 py-20 text-[#F8F2E9] md:px-10 md:py-28"><div className="mx-auto grid max-w-[1280px] gap-12 lg:grid-cols-[1fr_.7fr]"><div><p className="font-mono text-xs font-bold tracking-[0.18em] text-[#D1E0C8]">{c.feedbackEyebrow}</p><h2 className="mt-5 max-w-3xl font-display text-5xl leading-[.95] tracking-tight md:text-7xl">{c.feedbackTitle}</h2><p className="mt-7 max-w-2xl text-lg leading-8 text-[#E7EFDF]">{c.feedbackLead}</p></div><div className="self-end border border-[#F8F2E9]/25 bg-[#F8F2E9]/10 p-7"><Mail size={25} className="text-[#F0A687]" /><a href="mailto:claritleonelmnicol@gmail.com?subject=Villa%20Tomang%20Baru%20Field%20Guide%20feedback" className="mt-10 flex items-end justify-between gap-3 font-display text-3xl leading-tight hover:text-[#F0A687] md:text-4xl"><span>{c.feedback}</span><ArrowUpRight size={28} /></a><p className="mt-5 break-all font-mono text-xs text-[#D1E0C8]">claritleonelmnicol@gmail.com</p></div></div></section>

    <footer className="bg-[#31251F] px-5 py-12 text-[#D8CEBF] md:px-10"><div className="mx-auto grid max-w-[1280px] gap-10 lg:grid-cols-[1fr_.8fr_.55fr]"><div><div className="flex items-center gap-3"><img src={assets.logo} alt="" className="h-12 w-12" /><div><p className="font-display text-2xl text-[#F8F2E9]">Villa Tomang Baru</p><p className="font-mono text-[9px] font-bold tracking-[0.16em] text-[#9CB99A]">FIELD GUIDE</p></div></div><p className="mt-7 max-w-md text-sm leading-6">{c.footer}</p></div><div><p className="font-mono text-[10px] font-bold tracking-[0.16em] text-[#9CB99A]">NOTES</p><p className="mt-4 text-sm leading-6">{c.footer2}</p><p className="mt-4 text-xs leading-5 text-[#AA9B89]">{c.imageCredit}</p></div><div><p className="font-mono text-[10px] font-bold tracking-[0.16em] text-[#9CB99A]">POLICIES</p><div className="mt-4 grid gap-3 text-sm font-bold"><Link href="/privacy" className="hover:text-[#F0A687]">{c.legal[0]}</Link><Link href="/terms" className="hover:text-[#F0A687]">{c.legal[1]}</Link><Link href="/cookies" className="hover:text-[#F0A687]">{c.legal[2]}</Link></div></div></div><div className="mx-auto mt-12 max-w-[1280px] border-t border-[#F8F2E9]/10 pt-5 font-mono text-[10px] leading-5 text-[#AA9B89]">{c.copyright}</div></footer>
  </main>;
}
